apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resourcequota
  namespace: mynamespace
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "2"
    limits.memory: "4Gi"